service: cvs-tsk-edh-marshaller-inbound

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs14.x
  tracing: true # enable tracing
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

functions:
  getTestStations:
    handler: src/handler.handler
    events:
      - http:
          path: /{apiVersion}/test-stations/{testStationId}
          method: post
          request:
            parameters:
              paths:
                apiVersion: true
                testStationId: true
      - http:
          path: /{apiVersion}/test-stations/{testStationId}
          method: put
          request:
            parameters:
              paths:
                apiVersion: true
                testStationId: true

custom:
  serverless-offline:
    port: 3004
