functions:
  - createTestStation:
      method: POST
      path: /test-stations/{+proxy}
      proxy: :testStationId
      function: createTestStation
      event: apigateway
  - updateTestStation:
      method: PUT
      path: /test-stations/{+proxy}
      proxy: :testStationId
      function: updateTestStation
      event: apigateway
serverless:
  basePath: /${BRANCH}/:apiVersion
  port: 3024
targets:
  test-stations:
    queueName: cvs-edh-test-stations-${BRANCH}-queue
    swaggerSpecFile: API_Test_Stations_EDH->CVS_v1.yaml
    schemaItem: testStation
